# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '2f1d9d36-14a6-4aca-b15d-7970c2cee767'
  imageRepository: 'dbobolastackon'
  containerRegistry: 'stackonacr.azurecr.io'
  backdockerfilePath: '$(Build.SourcesDirectory)/backend/Dockerfile'
  frontdockerfilePath: '$(Build.SourcesDirectory)/frontend/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(frontdockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(backdockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    
- stage: Deploy
  displayName: Deploy stage
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DockerCompose@0
      displayName: Deploy with Docker Compose
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure for Students(4557848e-d9cd-43ac-bb93-c85d533f96c7)'
        azureContainerRegistry: '{"loginServer":"stackonacr.azurecr.io", "id" : "/subscriptions/4557848e-d9cd-43ac-bb93-c85d533f96c7/resourceGroups/stackonrg/providers/Microsoft.ContainerRegistry/registries/stackonacr"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run a Docker Compose command'
    - task: KubernetesManifest@0
      displayName: Deploy to Azure Kubernetes Service
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'stackon-service-kube-config'
