# Generated by Django 4.2 on 2023-04-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFTAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('volume', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sentiment', models.CharField(max_length=10)),
                ('next_1d_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('next_3d_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('next_7d_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trend', models.URLField()),
            ],
        ),
    ]
