# Generated by Django 4.2 on 2023-04-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftasset',
            name='asset_value',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20),
        ),
    ]
