# Generated by Django 4.2 on 2023-04-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0002_nftasset_asset_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFTPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('avatar', models.URLField()),
                ('timestamp', models.CharField(max_length=10)),
                ('post', models.TextField()),
            ],
        ),
    ]
