# Generated by Django 4.2 on 2023-04-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0003_nftposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftasset',
            name='image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nftasset',
            name='trend',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nftposts',
            name='avatar',
            field=models.CharField(max_length=100),
        ),
    ]
