# Generated by Django 4.2 on 2023-04-07 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0004_alter_nftasset_image_alter_nftasset_trend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_eth', models.TextField()),
                ('price_usd', models.TextField()),
                ('stack_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asset_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_1', to='stackon_app.nftasset')),
                ('asset_10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_10', to='stackon_app.nftasset')),
                ('asset_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_2', to='stackon_app.nftasset')),
                ('asset_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_3', to='stackon_app.nftasset')),
                ('asset_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_4', to='stackon_app.nftasset')),
                ('asset_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_5', to='stackon_app.nftasset')),
                ('asset_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_6', to='stackon_app.nftasset')),
                ('asset_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_7', to='stackon_app.nftasset')),
                ('asset_8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_8', to='stackon_app.nftasset')),
                ('asset_9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_9', to='stackon_app.nftasset')),
            ],
        ),
    ]
