# Generated by Django 4.2 on 2023-04-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0005_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='price_eth',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stack',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stack',
            name='stack_change',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
