# Generated by Django 4.2 on 2023-04-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0006_alter_stack_price_eth_alter_stack_price_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftasset',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
