# Generated by Django 4.2 on 2023-04-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0007_nftasset_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftposts',
            name='social_media',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
