# Generated by Django 4.2 on 2023-04-12 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0008_nftposts_social_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(max_length=255)),
                ('wallet_avatar', models.CharField(max_length=100)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('equity_eth', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('equity_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('equity_change', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('equity_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
        migrations.AlterField(
            model_name='stack',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stack',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_id', to='stackon_app.profile'),
        ),
    ]
