# Generated by Django 4.2 on 2023-04-13 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0009_profile_alter_stack_description_stack_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='status',
            field=models.CharField(choices=[('Owned', 'Owned'), ('Borrowed', 'Borrowed'), ('Public', 'Public')], default='Public', max_length=8),
        ),
        migrations.AlterField(
            model_name='stack',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_set', to='stackon_app.profile'),
        ),
    ]
