# Generated by Django 4.2 on 2023-04-19 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0010_stack_status_alter_stack_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='asset_11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_11', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_12', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_13', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_14', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_15', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_16', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_17', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_18', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_19',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_19', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_20',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_20', to='stackon_app.nftasset'),
        ),
    ]
