# Generated by Django 4.2 on 2023-04-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0011_stack_asset_11_stack_asset_12_stack_asset_13_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='total_eth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
