# Generated by Django 4.2 on 2023-04-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0012_stack_total_eth'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftasset',
            name='next_10d_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='nftasset',
            name='next_2d_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='nftasset',
            name='next_30d_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nftasset',
            name='next_1d_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nftasset',
            name='next_3d_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nftasset',
            name='next_7d_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
