# Generated by Django 4.2 on 2023-04-20 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0013_nftasset_next_10d_percent_nftasset_next_2d_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='asset_1',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='asset_10',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='asset_11',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='asset_12',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='asset_13',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='asset_14',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='asset_15',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='asset_16',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='asset_17',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='asset_18',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='asset_19',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='asset_2',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='asset_20',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='asset_3',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='asset_4',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='asset_5',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='asset_6',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='asset_7',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='asset_8',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='asset_9',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='status',
        ),
        migrations.AddField(
            model_name='profile',
            name='stack',
            field=models.ManyToManyField(to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_1', to='stackon_app.nftasset'),
        ),
    ]
