# Generated by Django 4.2 on 2023-04-20 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0014_remove_stack_asset_1_remove_stack_asset_10_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stack',
            old_name='asset',
            new_name='asset_1',
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_10', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_11', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_12', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_13', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_14', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_15', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_16', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_17', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_18', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_19',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_19', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_2', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_20',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_20', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_3', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_4', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_5', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_6', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_7', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_8', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='asset_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_asset_9', to='stackon_app.nftasset'),
        ),
        migrations.AddField(
            model_name='stack',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stack',
            name='name',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='stack',
            name='status',
            field=models.CharField(choices=[('Owned', 'Owned'), ('Borrowed', 'Borrowed'), ('Public', 'Public')], default='Public', max_length=8),
        ),
    ]
