# Generated by Django 4.2 on 2023-04-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0016_profile_next_14d_change_profile_next_1d_change_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nftasset',
            old_name='next_10d_percent',
            new_name='next_14d_percent',
        ),
    ]
