# Generated by Django 4.2 on 2023-04-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0017_rename_next_10d_percent_nftasset_next_14d_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftasset',
            name='active_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='active_change',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
