# Generated by Django 4.2 on 2023-04-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0019_rename_description_stack_nft_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='nft_seller',
            field=models.CharField(default='logo.ico', max_length=100),
        ),
    ]
