# Generated by Django 4.2 on 2023-05-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0021_geek_userinfo_remove_stack_nft_owner_delete_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='is_authenticated',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='stack',
            field=models.ManyToManyField(blank=True, to='stackon_app.nftasset'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='wallet_avatar',
            field=models.CharField(default='avatar4.png', max_length=100),
        ),
    ]
