# Generated by Django 4.2 on 2023-05-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0022_remove_userinfo_is_authenticated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(max_length=100)),
                ('description', models.TextField(default='Collection of over 99,999 NFTs. ')),
                ('volume_traded', models.DecimalField(decimal_places=2, max_digits=20)),
                ('floor_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('blockchain', models.CharField(choices=[('Ethereum', 'Ethereum'), ('Theta', 'Theta'), ('Solana', 'Solana'), ('Polygon', 'Polygon'), ('BNB', 'BNB'), ('Tezos', 'Tezos'), ('None', 'None')], default='None', max_length=20)),
                ('launch_time', models.CharField(choices=[('None', 'None'), ('1 Month', '1 Month'), ('3 Months', '3 Months'), ('6 Months', '6 Months'), ('1 Year', '1 Year'), ('2 Years', '2 Years'), ('5 Years', '5 Years')], default='None', max_length=20)),
                ('rarity', models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Epic', 'Epic'), ('Legendary', 'Legendary'), ('None', 'None')], default='None', max_length=20)),
                ('regulations', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO'), ('None', 'None')], default='None', max_length=20)),
                ('partnerships', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO'), ('None', 'None')], default='None', max_length=20)),
                ('technology_updates', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO'), ('None', 'None')], default='None', max_length=20)),
                ('security_incidents', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO'), ('None', 'None')], default='None', max_length=20)),
                ('all_influencers', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('all_investors', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('all_founders', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('all_community', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('all_social_media', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('twitter_influencers', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('twitter_investors', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('twitter_founders', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('twitter_community', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('all_twitter', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('reddit_influencers', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('reddit_investors', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('reddit_founders', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('reddit_community', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('all_reddit', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('telegram_influencers', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('telegram_investors', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('telegram_founders', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('telegram_community', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('all_telegram', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('discord_influencers', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('discord_investors', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('discord_founders', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('discord_community', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
                ('all_discord', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('None', 'None')], default='None', max_length=20)),
            ],
        ),
    ]
