# Generated by Django 4.2 on 2023-05-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0023_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='trend',
            field=models.CharField(default='graph.svg', max_length=100),
        ),
    ]
