# Generated by Django 4.2 on 2023-05-26 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0024_assets_trend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='short_name',
        ),
    ]
