# Generated by Django 4.2 on 2023-05-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0025_remove_assets_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='floor_price_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='assets',
            name='volume_traded_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
