# Generated by Django 4.2 on 2023-05-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0027_remove_assets_floor_price_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='trend_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='assets',
            name='floor_price_range',
            field=models.CharField(choices=[('ZEROFIFTY', '0 - 50'), ('FIFTYHUNDRED', '50 -99'), ('THOUSAND', '100 - 999'), ('HUNDREDTHOUSAND', '1000 - 99999'), ('MILLION', '99999 and Above'), ('None', 'None')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='assets',
            name='launch_time',
            field=models.CharField(choices=[('None', 'None'), ('ONEMONTH', '1 Month'), ('THREEMONTH', '3 Months'), ('SIXMONTH', '6 Months'), ('ONEYEAR', '1 Year'), ('TWOYEARS', '2 Years'), ('FIVEYEARS', '5 Years')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='assets',
            name='partnerships',
            field=models.CharField(choices=[('True', 'True'), ('None', 'None')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='assets',
            name='regulations',
            field=models.CharField(choices=[('True', 'True'), ('None', 'None')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='assets',
            name='security_incidents',
            field=models.CharField(choices=[('True', 'True'), ('None', 'None')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='assets',
            name='technology_updates',
            field=models.CharField(choices=[('True', 'True'), ('None', 'None')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='assets',
            name='volume_traded',
            field=models.CharField(default='1K', max_length=100),
        ),
        migrations.AlterField(
            model_name='assets',
            name='volume_traded_range',
            field=models.CharField(choices=[('BELOW10THOUSAND', 'Below 10,000'), ('FROM10_100THOUSAND', '10,000 - 99,999'), ('FROM100_1MILLION', '100,000 - 999,999'), ('FROM1_50MILLION', '1,000,000 - 49,999,999'), ('FROM50_500MILLION', '50,000,000 - 499,999,999'), ('FROM500_1BILLION', '500,000,000 - 999,999,999'), ('ABOVE1BILLION', '1,000,000,000 and Above'), ('None', 'None')], default='None', max_length=50),
        ),
    ]
