# Generated by Django 4.2 on 2023-05-26 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stackon_app', '0029_assets_blockchain_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilteredAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtered_assets', models.JSONField()),
                ('filtered_assets_texts', models.TextField(default='These are the top assets..')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
