# Generated by Django 4.2 on 2023-05-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0030_filteredassets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filteredassets',
            name='filtered_assets',
            field=models.JSONField(default=[{'description': 'The Bored Ape Yacht Club NFTs are a collection of 10,000 unique Bored Ape Non Fungible Tokens.', 'image': 'bored-ape-yacht-club.avif', 'name': 'Bored Ape Yacht Club'}, {'description': 'The CryptoPunks are 10,000 uniquely generated characters. No two are exactly alike.', 'image': 'crypto-punks.avif', 'name': 'CryptoPunks'}]),
        ),
        migrations.AlterField(
            model_name='filteredassets',
            name='filtered_assets_texts',
            field=models.TextField(default='Welcome here! Click on the Add Modifier to get started.'),
        ),
    ]
