# Generated by Django 4.2 on 2023-05-27 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0031_alter_filteredassets_filtered_assets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='all_community',
            new_name='overall_community',
        ),
        migrations.RenameField(
            model_name='assets',
            old_name='all_discord',
            new_name='overall_discord',
        ),
        migrations.RenameField(
            model_name='assets',
            old_name='all_founders',
            new_name='overall_founders',
        ),
        migrations.RenameField(
            model_name='assets',
            old_name='all_influencers',
            new_name='overall_influencers',
        ),
        migrations.RenameField(
            model_name='assets',
            old_name='all_investors',
            new_name='overall_investors',
        ),
        migrations.RenameField(
            model_name='assets',
            old_name='all_reddit',
            new_name='overall_reddit',
        ),
        migrations.RenameField(
            model_name='assets',
            old_name='all_social_media',
            new_name='overall_social_media',
        ),
        migrations.RenameField(
            model_name='assets',
            old_name='all_telegram',
            new_name='overall_telegram',
        ),
        migrations.RenameField(
            model_name='assets',
            old_name='all_twitter',
            new_name='overall_twitter',
        ),
    ]
