# Generated by Django 4.2 on 2023-05-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0032_rename_all_community_assets_overall_community_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geek',
            name='nft_status',
            field=models.CharField(choices=[('owned', 'Owned'), ('borrowed', 'Borrowed'), ('public', 'Public')], default='public', max_length=8),
        ),
    ]
