# Generated by Django 4.2 on 2023-05-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0033_alter_geek_nft_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geek',
            name='nft_status',
            field=models.CharField(choices=[('theta-geeks', 'Theta Geeks'), ('stackon-geeks', 'Stackon Geeks'), ('stackon-dev-geeks', 'Stackon Dev Geeks')], default='theta-geeks', max_length=100),
        ),
    ]
