# Generated by Django 4.2 on 2023-05-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0034_alter_geek_nft_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='geek',
            name='nft_pre_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geek',
            name='nft_features',
            field=models.ManyToManyField(blank=True, to='stackon_app.feature'),
        ),
    ]
