# Generated by Django 4.2 on 2023-05-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0035_feature_geek_nft_pre_description_geek_nft_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='geek',
            name='nft_collection',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='geek',
            name='nft_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
