# Generated by Django 4.2 on 2023-05-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0036_geek_nft_collection_alter_geek_nft_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geek',
            name='nft_status',
            field=models.CharField(choices=[('theta-geeks', 'Theta Geeks'), ('stackon-geeks', 'Stackon Geeks'), ('stackon-com-geeks', 'Stackon Community Geeks')], default='theta-geeks', max_length=100),
        ),
    ]
