# Generated by Django 4.2 on 2023-05-29 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0038_livestream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stackon_app.userinfo'),
        ),
    ]
