# Generated by Django 4.2 on 2023-05-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0039_alter_livestream_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='api_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='secret_key',
            field=models.TextField(blank=True),
        ),
    ]
