# Generated by Django 4.2 on 2023-05-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0040_userinfo_api_key_userinfo_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='status',
            field=models.CharField(choices=[('LIVE', 'LIVE'), ('ENDED', 'ENDED'), ('DRAFT', 'DRAFT')], default='LIVE', max_length=100),
        ),
    ]
