# Generated by Django 4.2 on 2023-05-30 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stackon_app', '0041_alter_livestream_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.TextField(blank=True)),
                ('wallet_avatar', models.CharField(default='avatar4.png', max_length=100)),
                ('api_key', models.TextField(blank=True)),
                ('secret_key', models.TextField(blank=True)),
                ('equity_eth', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('equity_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('equity_change', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('equity_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('active_change', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stack', models.ManyToManyField(blank=True, to='stackon_app.feature')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
