# Generated by Django 4.2 on 2023-05-31 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0042_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='mnemonic_phrase',
            field=models.TextField(blank=True),
        ),
    ]
