# Generated by Django 4.2 on 2023-05-31 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0043_accounts_mnemonic_phrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='private_key',
            field=models.TextField(blank=True),
        ),
    ]
