# Generated by Django 4.2 on 2023-05-31 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0045_contract_alter_filteredassets_filtered_assets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='discordModCollectionContractABI',
            new_name='stackonModCollectionContractABI',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='overallModCollectionContractABI',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='redditModCollectionContractABI',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='telegramModCollectionContractABI',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='twitterModCollectionContractABI',
        ),
    ]
