# Generated by Django 4.2 on 2023-06-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0049_accounts_free_mint'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='bnbGeekCollectionContractAddress',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ethereumGeekCollectionContractAddress',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='polygonGeekCollectionContractAddress',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='solanaGeekCollectionContractAddress',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='tezosGeekCollectionContractAddress',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='thetaGeekCollectionContractAddress',
            field=models.TextField(blank=True),
        ),
    ]
