# Generated by Django 4.2 on 2023-06-01 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stackon_app', '0050_contract_bnbgeekcollectioncontractaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stackon_app.accounts'),
        ),
    ]
