# Generated by Django 4.1.2 on 2022-10-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('volume', models.IntegerField()),
                ('tweets', models.IntegerField()),
                ('sentiment', models.CharField(max_length=200)),
                ('nftindex', models.CharField(max_length=200)),
                ('closeprice', models.IntegerField()),
            ],
        ),
    ]
