# Generated by Django 4.1.2 on 2022-10-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_collection_delete_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='open_price',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
    ]
